const https = require('https');
const fs = require('fs');

const URL = 'https://raw.githubusercontent.com/crhallberg/json-against-humanity/master/cah-all-full.json';
const OUTPUT_FILE = 'cards.js';

console.log(`Fetching cards from ${URL}...`);

https.get(URL, (res) => {
    let data = '';

    res.on('data', (chunk) => {
        data += chunk;
    });

    res.on('end', () => {
        try {
            const json = JSON.parse(data);

            if (Array.isArray(json)) {
                console.log(`JSON is array of ${json.length} items.`);

                // Find the Base Game pack
                const basePack = json.find(p => p.name === "CAH Base Set" || p.name === "Cards Against Humanity");


                if (basePack) {
                    console.log(`FOUND BASE PACK: ${basePack.name}`);

                    const cleanWhite = basePack.white.map(c => c.text);
                    const cleanBlack = basePack.black.map(c => ({ text: c.text, pick: c.pick }));

                    console.log(`Extracted: ${cleanWhite.length} White Cards and ${cleanBlack.length} Black Cards.`);

                    const fileContent = `// Auto-generated by fetch_cards.js (Base Game Only)
const WHITE_CARDS = ${JSON.stringify(cleanWhite, null, 2)};

const BLACK_CARDS = ${JSON.stringify(cleanBlack, null, 2)};

module.exports = {
    WHITE_CARDS,
    BLACK_CARDS
};
`;
                    fs.writeFileSync(OUTPUT_FILE, fileContent);
                    console.log(`Successfully wrote ${OUTPUT_FILE}`);

                } else {
                    console.error("Could not find pack named 'Cards Against Humanity'. Available names:");
                    json.slice(0, 10).forEach(p => console.log(`- ${p.name}`));
                }

            } else {
                console.error("Unexpected JSON structure: Not an array.");
            }

        } catch (err) {
            console.error('Error parsing JSON:', err);
        }
    });

}).on('error', (err) => {
    console.error('Error fetching data:', err);
});
