const fs = require('fs');
const { WHITE_CARDS, BLACK_CARDS } = require('./cards');

console.log(`Original: ${WHITE_CARDS.length} White, ${BLACK_CARDS.length} Black`);

// Dedupe White Cards (Strings)
const uniqueWhite = [...new Set(WHITE_CARDS)];

// Dedupe Black Cards (Objects - need deep comparison or check text)
const uniqueBlackStats = new Set();
const uniqueBlack = BLACK_CARDS.filter(card => {
    const key = card.text + '|' + card.pick;
    if (uniqueBlackStats.has(key)) return false;
    uniqueBlackStats.add(key);
    return true;
});

console.log(`New: ${uniqueWhite.length} White, ${uniqueBlack.length} Black`);

const fileContent = `// Auto-generated by fix_duplicates.js
const WHITE_CARDS = ${JSON.stringify(uniqueWhite, null, 2)};

const BLACK_CARDS = ${JSON.stringify(uniqueBlack, null, 2)};

module.exports = { WHITE_CARDS, BLACK_CARDS };
`;

fs.writeFileSync('./cards.js', fileContent);
console.log('Successfully rewrote cards.js with unique cards.');
